insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 1, 'Seamless empowering utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 2, 'Advanced motivating adapter', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 3, 'Phased full-range synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 4, 'Phased composite knowledge base', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 5, 'Cross-platform object-oriented software', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 1, 'Integrated regional hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 2, 'Inverse national structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 3, 'Programmable solution-oriented contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 4, 'Multi-lateral fresh-thinking standardization', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 5, 'Down-sized needs-based leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 1, 'Devolved high-level matrix', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 2, 'Re-engineered 24/7 core', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 3, 'Polarised high-level capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 4, 'Versatile zero tolerance project', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 5, 'Sharable system-worthy local area network', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 1, 'Organic client-server internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 2, 'Persistent system-worthy contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 3, 'Multi-lateral transitional analyzer', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 4, 'Monitored optimal neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 5, 'Persistent secondary toolset', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 1, 'Progressive motivating ability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 2, 'Cross-group non-volatile frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 3, 'Compatible disintermediate process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 4, 'De-engineered global capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 5, 'Implemented asymmetric access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 1, 'Configurable multi-tasking Graphical User Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 2, 'De-engineered grid-enabled knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 3, 'Optional even-keeled protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 4, 'Organized fresh-thinking protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 5, 'Universal actuating installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 1, 'Operative didactic internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 2, 'Front-line methodical neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 3, 'Grass-roots directional pricing structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 4, 'Upgradable stable complexity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 5, 'Profound 3rd generation focus group', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 1, 'Right-sized web-enabled budgetary management', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 2, 'Distributed needs-based throughput', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 3, 'Front-line value-added website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 4, 'Operative directional circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 5, 'Diverse local focus group', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 1, 'Inverse scalable contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 2, 'Intuitive bifurcated initiative', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 3, 'Adaptive zero tolerance architecture', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 4, 'Mandatory dedicated budgetary management', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 5, 'Advanced asynchronous extranet', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 1, 'Reactive analyzing installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 2, 'Vision-oriented systematic capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 3, 'Quality-focused radical migration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 4, 'Secured dedicated concept', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 5, 'Visionary bi-directional frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 1, 'Advanced zero defect hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 2, 'Upgradable attitude-oriented monitoring', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 3, 'Right-sized upward-trending productivity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 4, 'Sharable secondary array', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 5, 'Extended 24 hour synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 1, 'Phased 5th generation workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 2, 'Object-based non-volatile core', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 3, 'Centralized well-modulated installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 4, 'Down-sized systemic policy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 5, 'Polarised context-sensitive access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 1, 'Quality-focused analyzing strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 2, 'Optimized national website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 3, 'Centralized incremental methodology', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 4, 'Face to face static projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 5, 'Compatible disintermediate neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 1, 'Managed holistic database', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 2, 'Customer-focused reciprocal structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 3, 'Synchronised context-sensitive circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 4, 'Fully-configurable human-resource info-mediaries', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 5, 'Extended 5th generation infrastructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 1, 'Grass-roots fresh-thinking analyzer', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 2, 'Compatible regional Graphic Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 3, 'Expanded responsive capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 4, 'Open-source 24 hour time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 5, 'Configurable methodical pricing structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 1, 'Adaptive uniform process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 2, 'Stand-alone directional capability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 3, 'Optimized background customer loyalty', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 4, 'Advanced systematic software', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 5, 'Organized user-facing policy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 1, 'Virtual eco-centric protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 2, 'Synergized attitude-oriented orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 3, 'Digitized secondary throughput', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 4, 'Multi-layered content-based portal', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 5, 'Right-sized multimedia service-desk', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 1, 'Fundamental impactful encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 2, 'Multi-layered national installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 3, 'Reverse-engineered well-modulated process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 4, 'Diverse background emulation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 5, 'Multi-layered incremental workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 1, 'Automated optimal monitoring', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 2, 'Object-based regional conglomeration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 3, 'Polarised neutral array', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 4, 'Open-source non-volatile hub', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 5, 'Balanced uniform installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 1, 'Centralized disintermediate policy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 2, 'Robust leading edge internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 3, 'Switchable composite portal', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 4, 'Fundamental cohesive open system', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 5, 'Triple-buffered impactful architecture', 'Multiple Choice');
