insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 4, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (1, 1, 5, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 3, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (2, 2, 5, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 1, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 2, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 3, 'This is the correct answer', 'true');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (3, 3, 5, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 1, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 2, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 4, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (4, 4, 5, 'something random3', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 1, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 2, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 3, 'something random1', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 4, 'something random2', 'false');
insert into quiz_question_submissions (quiz_id, taker_id, question_id, answer_selected, is_correct) values (5, 5, 5, 'something random2', 'false');
