insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 1, 'Mandatory empowering function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 2, 'Managed contextually-based definition', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 3, 'Digitized actuating artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 4, 'Enterprise-wide uniform matrix', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 5, 'Universal human-resource orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 1, 'Automated bottom-line internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 2, 'De-engineered composite time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 3, 'Innovative demand-driven internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 4, 'Switchable methodical complexity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 5, 'Horizontal client-server strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 1, 'Decentralized scalable parallelism', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 2, 'Expanded responsive hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 3, 'Decentralized real-time solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 4, 'Focused optimizing hub', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 5, 'Implemented 24 hour hub', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 1, 'Enhanced 24 hour challenge', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 2, 'Realigned discrete initiative', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 3, 'Expanded 6th generation local area network', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 4, 'Integrated full-range projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 5, 'Multi-layered impactful website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 1, 'Multi-layered 24/7 knowledge base', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 2, 'Devolved background protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 3, 'Function-based executive capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 4, 'User-friendly leading edge matrices', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 5, 'Visionary stable support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 1, 'Secured responsive emulation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 2, 'Synergized intermediate task-force', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 3, 'Streamlined systemic strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 4, 'Managed interactive strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 5, 'Future-proofed optimizing solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 1, 'Down-sized coherent array', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 2, 'Diverse motivating neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 3, 'Cross-platform modular leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 4, 'Robust actuating attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 5, 'Open-source dedicated interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 1, 'Synergistic impactful approach', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 2, 'Front-line didactic circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 3, 'Fundamental analyzing installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 4, 'Total bifurcated infrastructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 5, 'Inverse reciprocal support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 1, 'Advanced radical framework', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 2, 'Streamlined client-server firmware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 3, 'Compatible transitional open system', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 4, 'Synergistic scalable secured line', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 5, 'Grass-roots incremental time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 1, 'Realigned exuding archive', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 2, 'Reverse-engineered zero defect hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 3, 'Enhanced didactic installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 4, 'Centralized multimedia protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 5, 'Advanced actuating workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 1, 'Triple-buffered bandwidth-monitored open system', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 2, 'Focused executive function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 3, 'Proactive secondary focus group', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 4, 'Object-based 24/7 success', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 5, 'Integrated foreground middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 1, 'Grass-roots encompassing strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 2, 'Triple-buffered real-time projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 3, 'Synergized impactful product', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 4, 'Cloned cohesive contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 5, 'Organized real-time hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 1, 'Stand-alone impactful policy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 2, 'Ergonomic zero tolerance monitoring', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 3, 'Sharable reciprocal encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 4, 'Polarised systemic pricing structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 5, 'Right-sized logistical orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 1, 'Reactive static workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 2, 'Stand-alone disintermediate support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 3, 'Front-line cohesive application', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 4, 'Object-based exuding capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 5, 'Business-focused global array', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 1, 'Polarised client-server firmware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 2, 'Adaptive 24/7 circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 3, 'Switchable user-facing challenge', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 4, 'Operative encompassing system engine', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 5, 'Multi-channelled radical leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 1, 'Cross-platform discrete policy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 2, 'Secured human-resource function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 3, 'Triple-buffered systemic synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 4, 'Exclusive non-volatile model', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 5, 'Phased object-oriented data-warehouse', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 1, 'Seamless value-added installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 2, 'Right-sized static utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 3, 'Organic fresh-thinking archive', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 4, 'Versatile analyzing analyzer', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 5, 'Multi-tiered bottom-line instruction set', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 1, 'Organic tertiary encryption', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 2, 'Down-sized clear-thinking synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 3, 'Re-engineered interactive protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 4, 'Decentralized 4th generation installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 5, 'Enterprise-wide empowering paradigm', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 1, 'Decentralized multimedia functionalities', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 2, 'Enhanced interactive knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 3, 'Organic leading edge ability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 4, 'Universal explicit capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 5, 'Synergistic high-level structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 1, 'Progressive asymmetric moratorium', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 2, 'Enterprise-wide 3rd generation structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 3, 'Polarised demand-driven conglomeration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 4, 'Universal encompassing artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 5, 'Universal logistical forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 1, 'Enhanced national intranet', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 2, 'Balanced leading edge structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 3, 'Function-based interactive alliance', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 4, 'Up-sized local contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 5, 'Future-proofed impactful budgetary management', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 1, 'Mandatory responsive attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 2, 'User-friendly web-enabled access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 3, 'Ergonomic web-enabled firmware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 4, 'Face to face actuating open system', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 5, 'Up-sized intermediate matrix', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 1, 'Stand-alone contextually-based instruction set', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 2, 'Universal systemic instruction set', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 3, 'Digitized full-range hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 4, 'Intuitive well-modulated migration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 5, 'Public-key optimal hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 1, 'Decentralized intermediate core', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 2, 'Assimilated human-resource synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 3, 'Synergistic logistical Graphic Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 4, 'Customer-focused explicit alliance', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 5, 'Business-focused real-time moderator', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 1, 'Customizable asymmetric hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 2, 'Cloned holistic approach', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 3, 'Reduced systematic implementation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 4, 'Streamlined human-resource Graphic Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 5, 'Networked multi-state internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 1, 'Streamlined object-oriented algorithm', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 2, 'Reduced explicit access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 3, 'Inverse 24/7 leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 4, 'Vision-oriented grid-enabled access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 5, 'Extended hybrid access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 1, 'Up-sized tertiary help-desk', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 2, 'Integrated zero tolerance strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 3, 'Balanced dynamic orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 4, 'Exclusive regional project', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 5, 'Team-oriented bifurcated utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 1, 'Persistent next generation customer loyalty', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 2, 'Reduced 5th generation productivity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 3, 'Public-key well-modulated neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 4, 'Exclusive analyzing core', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 5, 'Enhanced grid-enabled interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 1, 'Customer-focused optimizing groupware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 2, 'Reduced actuating hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 3, 'Assimilated foreground toolset', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 4, 'Sharable content-based access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 5, 'Centralized client-driven attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 1, 'Face to face demand-driven hub', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 2, 'Function-based multi-state strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 3, 'Optimized stable time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 4, 'Vision-oriented zero tolerance function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 5, 'Synergized even-keeled challenge', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 1, 'Function-based composite artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 2, 'Business-focused user-facing circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 3, 'Multi-channelled fault-tolerant middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 4, 'Persistent contextually-based approach', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 5, 'Distributed well-modulated architecture', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 1, 'Balanced modular workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 2, 'Proactive context-sensitive time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 3, 'Inverse encompassing process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 4, 'Function-based upward-trending superstructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 5, 'Extended client-driven encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 1, 'Up-sized cohesive knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 2, 'Centralized optimal knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 3, 'Function-based systematic superstructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 4, 'Universal asymmetric leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 5, 'Persistent disintermediate function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 1, 'Reduced web-enabled superstructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 2, 'Intuitive clear-thinking utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 3, 'Integrated bottom-line encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 4, 'Phased human-resource task-force', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 5, 'Ameliorated optimal middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 1, 'Phased zero tolerance encryption', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 2, 'Devolved leading edge middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 3, 'Focused empowering parallelism', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 4, 'Diverse contextually-based success', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 5, 'Mandatory systematic utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 1, 'Compatible non-volatile intranet', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 2, 'Triple-buffered didactic infrastructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 3, 'Extended 24 hour info-mediaries', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 4, 'Profit-focused high-level frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 5, 'Horizontal bandwidth-monitored interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 1, 'Vision-oriented asymmetric website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 2, 'Visionary mobile product', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 3, 'Function-based bandwidth-monitored hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 4, 'Self-enabling client-driven forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 5, 'Open-architected well-modulated standardization', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 1, 'Object-based homogeneous attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 2, 'Ergonomic tangible ability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 3, 'Fully-configurable multi-state moratorium', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 4, 'Expanded real-time projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 5, 'Future-proofed heuristic artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 1, 'Implemented foreground capability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 2, 'Reactive foreground benchmark', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 3, 'Fully-configurable modular forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 4, 'Organized foreground throughput', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 5, 'Monitored didactic leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 1, 'Fundamental hybrid support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 2, 'Future-proofed logistical definition', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 3, 'Virtual next generation website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 4, 'Fully-configurable heuristic attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 5, 'Visionary regional project', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 1, 'I w_nt to th_ park: Which letters are missing from this sentence?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 2, 'What does TV stand for?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 3, 'Which word is an adjective?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 4, 'The young mother looked proudly at her baby: Which words are the verb and adverb?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 5, 'Which of these is the upper case letter for letter: s?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 1, 'What is 8 + 3?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 2, 'What is half of 12?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 3, 'Which of the following numbers is odd?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 4, 'Which one of these is best in a healthy diet?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 5, 'Which parts of a tree grow into the soil?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 1, 'What can we not live without?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 2, 'Alison teaches children in a school. Alison is a:', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 3, 'There is a bright, blue sky. The light is dazzling. The weather is:', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 4, 'Which is the biggest continent?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 5, 'Which is the coolest season?', 'Multiple Choice');