insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 1, 'Progressive interactive application', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 2, 'Expanded foreground hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 3, 'Persistent multi-state frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 4, 'Centralized composite circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 5, 'Robust regional challenge', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 1, 'Progressive contextually-based model', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 2, 'Profound full-range functionalities', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 3, 'Up-sized 3rd generation archive', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 4, 'Re-engineered eco-centric application', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 5, 'Multi-lateral next generation artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 1, 'Object-based motivating initiative', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 2, 'Future-proofed reciprocal encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 3, 'Compatible optimal conglomeration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 4, 'Self-enabling client-driven functionalities', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 5, 'Mandatory uniform core', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 1, 'Reduced secondary strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 2, 'Multi-lateral global capability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 3, 'Progressive leading edge encryption', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 4, 'Enhanced tangible middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 5, 'Multi-channelled 6th generation definition', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 1, 'Monitored systemic data-warehouse', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 2, 'Re-contextualized cohesive extranet', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 3, 'Assimilated composite emulation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 4, 'Public-key exuding knowledge base', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 5, 'Cross-platform impactful architecture', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 1, 'Upgradable leading edge monitoring', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 2, 'Streamlined mission-critical hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 3, 'Assimilated transitional algorithm', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 4, 'Extended radical portal', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 5, 'Operative eco-centric access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 1, 'Customer-focused 3rd generation benchmark', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 2, 'Virtual static firmware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 3, 'Horizontal context-sensitive model', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 4, 'Right-sized human-resource solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 5, 'Multi-layered didactic encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 1, 'Advanced motivating Graphic Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 2, 'Expanded heuristic forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 3, 'Profound web-enabled process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 4, 'Implemented bandwidth-monitored concept', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 5, 'Business-focused intangible info-mediaries', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 1, 'Innovative foreground success', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 2, 'Operative client-server productivity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 3, 'Face to face asynchronous process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 4, 'Re-contextualized stable Graphical User Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 5, 'Fundamental asymmetric definition', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 1, 'Virtual disintermediate contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 2, 'Face to face upward-trending functionalities', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 3, 'User-centric maximized migration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 4, 'Cross-platform next generation knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 5, 'Adaptive methodical orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 1, 'Synchronised logistical projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 2, 'Reverse-engineered holistic complexity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 3, 'Customizable foreground implementation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 4, 'Progressive asynchronous archive', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 5, 'Multi-channelled 4th generation matrices', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 1, 'Upgradable disintermediate analyzer', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 2, 'Extended incremental product', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 3, 'Organized heuristic data-warehouse', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 4, 'Enterprise-wide dedicated time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 5, 'Function-based user-facing encryption', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 1, 'Virtual next generation forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 2, 'Front-line user-facing paradigm', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 3, 'Quality-focused real-time architecture', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 4, 'Advanced 3rd generation structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 5, 'Multi-tiered next generation neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 1, 'Multi-tiered content-based forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 2, 'Synchronised responsive encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 3, 'Up-sized contextually-based website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 4, 'Fundamental empowering system engine', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 5, 'Virtual exuding success', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 1, 'Profound system-worthy process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 2, 'Function-based exuding time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 3, 'Down-sized grid-enabled synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 4, 'Enterprise-wide zero tolerance installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 5, 'Automated national capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 1, 'Synchronised upward-trending functionalities', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 2, 'Diverse coherent service-desk', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 3, 'Optional radical standardization', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 4, 'Managed 5th generation superstructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 5, 'Profit-focused local strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 1, 'Open-architected systemic customer loyalty', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 2, 'Enhanced bottom-line concept', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 3, 'User-centric empowering function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 4, 'Mandatory contextually-based model', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 5, 'Multi-channelled full-range interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 1, 'Streamlined reciprocal emulation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 2, 'Extended radical architecture', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 3, 'Switchable upward-trending installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 4, 'Reverse-engineered high-level implementation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 5, 'Sharable needs-based adapter', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 1, 'Upgradable static toolset', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 2, 'Customer-focused incremental budgetary management', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 3, 'Synergized homogeneous array', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 4, 'Polarised composite website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 5, 'Multi-layered asynchronous projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 1, 'Business-focused neutral Graphical User Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 2, 'Multi-channelled fresh-thinking time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 3, 'Self-enabling asymmetric archive', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 4, 'Right-sized human-resource time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 5, 'Ameliorated leading edge budgetary management', 'Multiple Choice');
