insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 1, 'Mandatory empowering function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 2, 'Managed contextually-based definition', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 3, 'Digitized actuating artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 4, 'Enterprise-wide uniform matrix', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (1, 5, 'Universal human-resource orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 1, 'Automated bottom-line internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 2, 'De-engineered composite time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 3, 'Innovative demand-driven internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 4, 'Switchable methodical complexity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (2, 5, 'Horizontal client-server strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 1, 'Decentralized scalable parallelism', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 2, 'Expanded responsive hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 3, 'Decentralized real-time solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 4, 'Focused optimizing hub', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (3, 5, 'Implemented 24 hour hub', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 1, 'Enhanced 24 hour challenge', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 2, 'Realigned discrete initiative', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 3, 'Expanded 6th generation local area network', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 4, 'Integrated full-range projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (4, 5, 'Multi-layered impactful website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 1, 'Multi-layered 24/7 knowledge base', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 2, 'Devolved background protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 3, 'Function-based executive capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 4, 'User-friendly leading edge matrices', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (5, 5, 'Visionary stable support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 1, 'Secured responsive emulation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 2, 'Synergized intermediate task-force', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 3, 'Streamlined systemic strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 4, 'Managed interactive strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (6, 5, 'Future-proofed optimizing solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 1, 'Down-sized coherent array', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 2, 'Diverse motivating neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 3, 'Cross-platform modular leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 4, 'Robust actuating attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (7, 5, 'Open-source dedicated interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 1, 'Synergistic impactful approach', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 2, 'Front-line didactic circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 3, 'Fundamental analyzing installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 4, 'Total bifurcated infrastructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (8, 5, 'Inverse reciprocal support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 1, 'Advanced radical framework', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 2, 'Streamlined client-server firmware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 3, 'Compatible transitional open system', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 4, 'Synergistic scalable secured line', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (9, 5, 'Grass-roots incremental time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 1, 'Realigned exuding archive', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 2, 'Reverse-engineered zero defect hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 3, 'Enhanced didactic installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 4, 'Centralized multimedia protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (10, 5, 'Advanced actuating workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 1, 'Triple-buffered bandwidth-monitored open system', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 2, 'Focused executive function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 3, 'Proactive secondary focus group', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 4, 'Object-based 24/7 success', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (11, 5, 'Integrated foreground middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 1, 'Grass-roots encompassing strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 2, 'Triple-buffered real-time projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 3, 'Synergized impactful product', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 4, 'Cloned cohesive contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (12, 5, 'Organized real-time hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 1, 'Stand-alone impactful policy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 2, 'Ergonomic zero tolerance monitoring', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 3, 'Sharable reciprocal encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 4, 'Polarised systemic pricing structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (13, 5, 'Right-sized logistical orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 1, 'Reactive static workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 2, 'Stand-alone disintermediate support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 3, 'Front-line cohesive application', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 4, 'Object-based exuding capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (14, 5, 'Business-focused global array', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 1, 'Polarised client-server firmware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 2, 'Adaptive 24/7 circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 3, 'Switchable user-facing challenge', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 4, 'Operative encompassing system engine', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (15, 5, 'Multi-channelled radical leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 1, 'Cross-platform discrete policy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 2, 'Secured human-resource function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 3, 'Triple-buffered systemic synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 4, 'Exclusive non-volatile model', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (16, 5, 'Phased object-oriented data-warehouse', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 1, 'Seamless value-added installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 2, 'Right-sized static utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 3, 'Organic fresh-thinking archive', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 4, 'Versatile analyzing analyzer', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (17, 5, 'Multi-tiered bottom-line instruction set', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 1, 'Organic tertiary encryption', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 2, 'Down-sized clear-thinking synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 3, 'Re-engineered interactive protocol', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 4, 'Decentralized 4th generation installation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (18, 5, 'Enterprise-wide empowering paradigm', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 1, 'Decentralized multimedia functionalities', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 2, 'Enhanced interactive knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 3, 'Organic leading edge ability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 4, 'Universal explicit capacity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (19, 5, 'Synergistic high-level structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 1, 'Progressive asymmetric moratorium', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 2, 'Enterprise-wide 3rd generation structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 3, 'Polarised demand-driven conglomeration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 4, 'Universal encompassing artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (20, 5, 'Universal logistical forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 1, 'Enhanced national intranet', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 2, 'Balanced leading edge structure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 3, 'Function-based interactive alliance', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 4, 'Up-sized local contingency', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (21, 5, 'Future-proofed impactful budgetary management', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 1, 'Mandatory responsive attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 2, 'User-friendly web-enabled access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 3, 'Ergonomic web-enabled firmware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 4, 'Face to face actuating open system', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (22, 5, 'Up-sized intermediate matrix', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 1, 'Stand-alone contextually-based instruction set', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 2, 'Universal systemic instruction set', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 3, 'Digitized full-range hardware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 4, 'Intuitive well-modulated migration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (23, 5, 'Public-key optimal hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 1, 'Decentralized intermediate core', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 2, 'Assimilated human-resource synergy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 3, 'Synergistic logistical Graphic Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 4, 'Customer-focused explicit alliance', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (24, 5, 'Business-focused real-time moderator', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 1, 'Customizable asymmetric hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 2, 'Cloned holistic approach', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 3, 'Reduced systematic implementation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 4, 'Streamlined human-resource Graphic Interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (25, 5, 'Networked multi-state internet solution', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 1, 'Streamlined object-oriented algorithm', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 2, 'Reduced explicit access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 3, 'Inverse 24/7 leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 4, 'Vision-oriented grid-enabled access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (26, 5, 'Extended hybrid access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 1, 'Up-sized tertiary help-desk', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 2, 'Integrated zero tolerance strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 3, 'Balanced dynamic orchestration', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 4, 'Exclusive regional project', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (27, 5, 'Team-oriented bifurcated utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 1, 'Persistent next generation customer loyalty', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 2, 'Reduced 5th generation productivity', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 3, 'Public-key well-modulated neural-net', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 4, 'Exclusive analyzing core', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (28, 5, 'Enhanced grid-enabled interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 1, 'Customer-focused optimizing groupware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 2, 'Reduced actuating hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 3, 'Assimilated foreground toolset', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 4, 'Sharable content-based access', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (29, 5, 'Centralized client-driven attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 1, 'Face to face demand-driven hub', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 2, 'Function-based multi-state strategy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 3, 'Optimized stable time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 4, 'Vision-oriented zero tolerance function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (30, 5, 'Synergized even-keeled challenge', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 1, 'Function-based composite artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 2, 'Business-focused user-facing circuit', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 3, 'Multi-channelled fault-tolerant middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 4, 'Persistent contextually-based approach', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (31, 5, 'Distributed well-modulated architecture', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 1, 'Balanced modular workforce', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 2, 'Proactive context-sensitive time-frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 3, 'Inverse encompassing process improvement', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 4, 'Function-based upward-trending superstructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (32, 5, 'Extended client-driven encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 1, 'Up-sized cohesive knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 2, 'Centralized optimal knowledge user', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 3, 'Function-based systematic superstructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 4, 'Universal asymmetric leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (33, 5, 'Persistent disintermediate function', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 1, 'Reduced web-enabled superstructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 2, 'Intuitive clear-thinking utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 3, 'Integrated bottom-line encoding', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 4, 'Phased human-resource task-force', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (34, 5, 'Ameliorated optimal middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 1, 'Phased zero tolerance encryption', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 2, 'Devolved leading edge middleware', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 3, 'Focused empowering parallelism', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 4, 'Diverse contextually-based success', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (35, 5, 'Mandatory systematic utilisation', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 1, 'Compatible non-volatile intranet', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 2, 'Triple-buffered didactic infrastructure', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 3, 'Extended 24 hour info-mediaries', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 4, 'Profit-focused high-level frame', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (36, 5, 'Horizontal bandwidth-monitored interface', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 1, 'Vision-oriented asymmetric website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 2, 'Visionary mobile product', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 3, 'Function-based bandwidth-monitored hierarchy', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 4, 'Self-enabling client-driven forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (37, 5, 'Open-architected well-modulated standardization', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 1, 'Object-based homogeneous attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 2, 'Ergonomic tangible ability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 3, 'Fully-configurable multi-state moratorium', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 4, 'Expanded real-time projection', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (38, 5, 'Future-proofed heuristic artificial intelligence', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 1, 'Implemented foreground capability', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 2, 'Reactive foreground benchmark', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 3, 'Fully-configurable modular forecast', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 4, 'Organized foreground throughput', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (39, 5, 'Monitored didactic leverage', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 1, 'Fundamental hybrid support', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 2, 'Future-proofed logistical definition', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 3, 'Virtual next generation website', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 4, 'Fully-configurable heuristic attitude', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (40, 5, 'Visionary regional project', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 1, 'I w_nt to th_ park: Which letters are missing from this sentence?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 2, 'What does TV stand for?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 3, 'Which word is an adjective?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 4, 'The young mother looked proudly at her baby: Which words are the verb and adverb?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (41, 5, 'Which of these is the upper case letter for letter: s?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 1, 'What is 8 + 3?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 2, 'What is half of 12?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 3, 'Which of the following numbers is odd?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 4, 'Which one of these is best in a healthy diet?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (42, 5, 'Which parts of a tree grow into the soil?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 1, 'What can we not live without?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 2, 'Alison teaches children in a school. Alison is a:', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 3, 'There is a bright, blue sky. The light is dazzling. The weather is:', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 4, 'Which is the biggest continent?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (43, 5, 'Which is the coolest season?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (44, 1, 'Tomato begins with the letter t: which letter follows t in the alphabet?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (44, 2, 'Which sentence is perfect?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (44, 3, 'Which group does the word hammer belong to?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (44, 4, 'Which of these is a question?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (44, 5, 'The whale was huge. What could we use instead of the word: huge?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (45, 1, 'What is the total of 3, 4 and 6?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (45, 2, 'What is the quarter of 12?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (45, 3, 'What are the next two numbers in this sequence: 27, 28, 29, 30?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (45, 4, 'What do we use to measure temperature?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (45, 5, 'Hannah is stirring a drink with a spoon. The spoon is a _____.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (46, 1, 'Many trees lose their leaves in October and November. What season is this?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (46, 2, 'When Shakespeare was alive, many people watched comedies, dramas and romance. Where did they do this?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (46, 3, 'Mozart, Beethoven and Bach were all famous...', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (46, 4, 'Sam’s teacher asks him to find out what shape Italy is. Sam looks in a big book of maps. Where does Sam look to find a map of Italy?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (46, 5, 'Mr Smith ploughs the fields. He uses a _______ to pull the plough.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (47, 1, 'If it''s the morning, which abbreviation do we use to show it?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (47, 2, 'Put these words in alphabetical order: school, teacher, pupil, book, work.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (47, 3, 'Which of these is the correct way to write this country''s name?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (47, 4, 'Which of these words would you write ''an'' in front of?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (47, 5, 'The concert will commence at 8 o''clock.'' Which word can we use instead of ''commence''?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (48, 1, 'What is 50 x 2?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (48, 2, 'How many hours are there in a day?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (48, 3, 'What is 1⁄4 of a kilometre?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (48, 4, 'Which one of these is the best way to keep fit?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (48, 5, 'Some animals can move quickly. Some animals move slowly. The tortoise moves slowly. Which one of these animals moves slowly?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (49, 1, 'What drink do we get from cows?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (49, 2, 'What is used to catch fish in the sea?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (49, 3, 'Andrew operates on people who are ill. Andrew is a:', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (49, 4, 'Christopher Columbus was a great explorer noted for discovering what?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (49, 5, 'Martin Luther King fought passionately, but without violence, to show what?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (50, 1, 'Find the adjectives in the sentence: The forest was dark and spooky.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (50, 2, 'Which one of the following words is NOT a synonym for ''odour''?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (50, 3, 'Read the sentence and find the connectives and conjunctions. We could always play a board game if the rain doesn''t stop.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (50, 4, 'Choose the correct spellings: If you ____ a bird, it will ____ away.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (50, 5, 'Choose the correct option: You are eating breakfast.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (51, 1, '75 subtract 40.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (51, 2, 'What does this symbol mean >?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (51, 3, 'What does the digit 4 represent in 3.4?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (51, 4, 'What does adaptation mean?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (51, 5, 'If it is winter in the Northern Hemisphere, what season is it in the Southern Hemisphere?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (52, 1, 'To make a computer work, algorithms have to be turned into ____.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (52, 2, 'Computers need algorithms to work. They need to be told the steps to make things happen. An algorithm is like a list of instructions. But it’s not just computers that need instructions. We do, too. Which one of these everyday examples is an algorithm?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (52, 3, 'Which of these is NOT affected by the weather?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (52, 4, 'What is the name of the place where rocks are extracted from the ground?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (52, 5, 'Which century do we live in?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (53, 1, 'Choose the list that has been alphabetised correctly.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (53, 2, 'Look at the four word choices for each sentence - three are adverbs and one is not. Select the word which is NOT an adverb: The room was ____ quiet.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (53, 3, 'Choose the correct pronouns to complete the sentence: Mom asked ____ what we wanted for tea, so ____ asked for spaghetti.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (53, 4, 'Find the verbs in the sentence: She runs very fast, but I think I am faster.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (53, 5, 'The prefix ''un-'' (as in ''unhappy'') means .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (54, 1, 'What is double 47?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (54, 2, 'Which is the smallest of these fractions?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (54, 3, 'How can we write 2 and half metres in decimals?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (54, 4, 'The plant kingdom is divided into two important groups. What are they?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (54, 5, 'When you contract your bicep, what happens?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (55, 1, 'How many years between 400 BCE and 400 CE?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (55, 2, 'When did World War II begin?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (55, 3, 'What is the process called when water turns into a gas and rises into the sky?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (55, 4, 'Which is NOT one of the 3 Rs?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (55, 5, 'Both computers and phones have these. You look at them.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (56, 1, 'The prefix ''sub-'' (as in ''subway'') means .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (56, 2, 'Look at the word and choose its correct plural: Box', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (56, 3, 'Ice cream is dripping down your chin: Change this sentence to the first person.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (56, 4, 'Choose the correct spellings: ____ the snake looked smooth, it was actually very ____.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (56, 5, 'What is a slogan?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (57, 1, 'Which gives the answer 43?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (57, 2, 'I have four ribbons measuring 34mm, 55mm, 87mm and 123mm. What is their total length in cm?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (57, 3, 'The ratio between blue boxes and yellow boxes is 3:2. If there are 4 yellow boxes how many blue boxes are there?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (57, 4, 'What forces are exerted by magnets?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (57, 5, 'Which is the coloured part of the eye?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (58, 1, 'Which one of these helps you to search the internet?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (58, 2, 'What does www stand for?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (58, 3, 'In the school office the secretary is adding up money for a school trip. She adds up the money on a ________.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (58, 4, 'Which climate receives the most rainfall?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (58, 5, 'What is the name given to people who dig to find old things in the ground?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (59, 1, 'Select the adjectives in the following sentence: A small grey mouse frightened the timid little child.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (59, 2, 'Select the antonym for: Awake', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (59, 3, 'Which one is correct?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (59, 4, 'Which word means ''belonging to them''?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (59, 5, 'Select the abstract noun to complete the following sentence. Working together needs .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (60, 1, 'Simplify 5a + 7a.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (60, 2, 'What is the next square number after 9?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (60, 3, 'What is 75.3 - 3.18?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (60, 4, 'Which is the largest planet in our solar system?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (60, 5, 'Which of the following is NOT a touching force?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (61, 1, 'Which word means any phase in history?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (61, 2, 'What barrier was said to divide Europe?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (61, 3, 'Click the correct answer for the following definition. A material made of fibres, a textile or cloth', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (61, 4, 'Which problem is not caused by burning fossil fuels?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (61, 5, 'Which of these statements is true?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (62, 1, 'Find the adverb(s) in the following: Interesting writing is produced by using adverbs well.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (62, 2, 'What is the antonym for: Enemy?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (62, 3, 'Which one means ''To gain''?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (62, 4, 'Find the purpose of the following well-known mnemonic: i before e except after c', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (62, 5, 'Select the correct affixes (an affix = prefix or suffix) for the following word.  ____appoint_____', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (63, 1, 'The number 24 has eight factors. Seven of the factors are 1, 2, 3, 4, 6, 12 and 24. What is the missing factor?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (63, 2, 'Which of these is a prime number?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (63, 3, 'What is the square root of 64 x 144?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (63, 4, 'The Earth spins round on its axis .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (63, 5, 'Which of the following organs is MOST damaged by smoking?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (64, 1, 'Trees give out which gas?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (64, 2, 'Evidence that is one-sided or unfair is said to be .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (64, 3, 'What was set up in 1945 to try and bring world peace?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (64, 4, 'Click the correct answer for the following definition: A portion of a book or document, incorporated distinctly in another work', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (64, 5, 'Which of these has the highest population density?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (65, 1, 'Choose the correct definition for the following term: Protagonist', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (65, 2, 'Choose the correct definition for the following term: Oxymoron', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (65, 3, 'See if you can find the synonym for the following word: Release', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (65, 4, 'Complete the following popular simile. I was very tired last night; I slept like .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (65, 5, 'Find a rhyme for: sheep.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (66, 1, 'If x > 3, what is the smallest integer that x can be?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (66, 2, 'You can never work out the exact area of a circle; what is the proof?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (66, 3, 'Which of the following equations means exactly the same as 2x + 3y = 13?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (66, 4, 'A cheetah runs at 100 km/h. How long will it take to run 100 metres?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (66, 5, 'Which type of rock has been formed from hot liquid rock called magma?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (67, 1, 'Using historical outcomes to draw conclusions about an event is…?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (67, 2, 'Click the correct answer for the following definition. Metaphorical, as opposed to literal; using figures; as of the use of ''cats and dogs'' in the phrase ''It''s raining cats and dogs''', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (67, 3, 'Bauxite is a mineral that can be made into what?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (67, 4, 'Which word describes goods transported in bulk?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (67, 5, 'The leader of the U.N. has what title?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (68, 1, 'Complete the sentence. That is the factory in ...... my Dad used to work.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (68, 2, 'Complete the sentence. Gordon, ...... nephew you met yesterday, will be visiting later.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (68, 3, 'Complete the sentence. There''s the book ...... I thought I''d lost.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (68, 4, 'Complete the sentence. The woman ...... said hello was my old dance teacher.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (68, 5, 'Complete the sentence. The van, ...... was stopped earlier today by police, turned out to be driven by the men suspected of last week''s bank robbery.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (69, 1, 'Which of the following is essential to a balanced diet?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (69, 2, 'Which of the following foods contains carbohydrates?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (69, 3, 'The level of cholesterol in your body is determined by what?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (69, 4, 'What is 3/5 of 40?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (69, 5, 'An element is made up from what?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (70, 1, 'Which of the following statements about plastic waste is untrue?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (70, 2, 'The carbon footprint measures ...', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (70, 3, 'Which of the following is not a factor that has influenced globalisation?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (70, 4, 'Which of the following is not a type of short-term migration?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (70, 5, 'Which of the following is a push factor for migration?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (71, 1, 'Choose the answer which best paraphrases the following. Before making their permanent move to France, the couple spent three years learning the language.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (71, 2, 'Which of the following is an example of gender-neutral language?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (71, 3, '''Doctor escapes jail for botched surgery'' - Which are the emotive words in this headline?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (71, 4, 'They were ...... expected by nine o''clock.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (71, 5, 'They were ...... expected by nine o''clock.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (72, 1, 'Some people follow special diets to reduce their weight. One of these is called the Atkins diet which is very low in carbohydrates. This forces the body to do what?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (72, 2, 'Amelia is going on a holiday to Italy, so she’ll have to purchase some euros. How many euros will she get for 375 dollars if the exchange rate is 1 dollar = 0.64 euro?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (72, 3, 'Which of the following give the charges in order for the proton, neutron and electron?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (72, 4, 'According to Darwin, new species evolve by which process?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (72, 5, 'What are biofuels?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (73, 1, 'Which of the following activities does not contribute directly to a person''s carbon footprint?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (73, 2, 'Where do hurricanes usually form?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (73, 3, 'Which of the following is a negative impact of globalization?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (73, 4, 'What does the term emigration mean?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (73, 5, 'Which of the following distances are equivalent?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (74, 1, 'Despite their ......, they were expected in the director''s office ......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (74, 2, 'Complete the following sentence: Here ...... the key and the map ...... you lent to me.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (74, 3, 'Complete the following sentence: ...... the main course ...... the dessert was offered to .......or .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (74, 4, 'Complete the following sentence: The silver, size four shoes ...... were in the charity shop''s window had been .......', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (74, 5, 'Complete the following sentence: Each of the pupils ...... been given a pencil, a rubber and a ruler in preparation for the exam.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (75, 1, 'Place the following fractions in ascending order: 5/8, 1/6, 3/4.', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (75, 2, 'Which of the following elements is not found in CaHCO3?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (75, 3, 'Where are the electrons found?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (75, 4, 'Which one of the following provides strong evidence for Darwin''s theory of evolution?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (75, 5, 'Which impurity in fuels causes acid rain when it burns?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (76, 1, 'To be called a hurricane, the wind speed in a storm must be ...', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (76, 2, 'To which environmental issue is the carbon footprint linked?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (76, 3, 'A positive benefit of globalization is ...', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (76, 4, 'How is a refugee defined?', 'Multiple Choice');
insert into quiz_questions (quiz_id, question_number, question, question_type) values (76, 5, 'The GDP of Bangladesh in 2014 was 173 billion US dollars. In 2015, this had increased to 195 billion US dollars. What is the approximate percentage increase?', 'Multiple Choice');